trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .Azure/
      - README.md
stages:
- stage: Build
  jobs:
  - job: Build
    displayName: 'Build artifacts'
    pool:
      vmImage: windows-latest
    continueOnError: false
    steps:
    - task: UseNode@1
      inputs:
        version: '16.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        npm run build
      displayName: 'npm build'
    - script: |
       ls -la
      displayName: 'List files'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish npm artifacts'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/build'
        ArtifactName: 'drop'
        publishLocation: Container

- stage: Dev
  jobs:
  - deployment: DeploytoDev
    displayName: 'Deploying to DEV'
    pool:
      vmImage: windows-latest
    environment: staticwebsite-dev
    continueOnError: false
    variables:
      - group: staticwebsite-dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: replacetokens@5
            inputs:
              targetFiles: '$(Pipeline.Workspace)/drop/**/*'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          - task: AzureFileCopy@5
            inputs:
              SourcePath: '$(Pipeline.Workspace)/drop/*'
              azureSubscription: 'Visual Studio Enterprise(66dbee39-6412-426f-b432-f8ddd74175a3)'
              Destination: 'AzureBlob'
              storage: '$(storageaccount)'
              ContainerName: '$web'

- stage: Hml
  jobs:
  - deployment: DeploytoHml
    displayName: 'Deploying to HML'
    pool:
      vmImage: windows-latest
    environment: staticwebsite-hml
    continueOnError: false
    variables:
      - group: staticwebsite-hml
    strategy:
      runOnce:
        deploy:
          steps:
          - task: replacetokens@5
            inputs:
              targetFiles: '$(Pipeline.Workspace)/drop/**/*'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          - task: AzureFileCopy@5
            inputs:
              SourcePath: '$(Pipeline.Workspace)/drop/*'
              azureSubscription: 'Visual Studio Enterprise(66dbee39-6412-426f-b432-f8ddd74175a3)'
              Destination: 'AzureBlob'
              storage: '$(storageaccount)'
              ContainerName: '$web'

- stage: Prd
  jobs:
  - deployment: DeploytoPrd
    displayName: 'Deploying to PRD'
    pool:
      vmImage: windows-latest
    environment: staticwebsite-prd
    continueOnError: false
    variables:
      - group: staticwebsite-prd
    strategy:
      runOnce:
        deploy:
          steps:
          - task: replacetokens@5
            inputs:
              targetFiles: '$(Pipeline.Workspace)/drop/**/*'
              encoding: 'auto'
              tokenPattern: 'default'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              actionOnNoFiles: 'continue'
              enableTransforms: false
              enableRecursion: false
              useLegacyPattern: false
              enableTelemetry: true
          - task: AzureFileCopy@5
            inputs:
              SourcePath: '$(Pipeline.Workspace)/drop/*'
              azureSubscription: 'Visual Studio Enterprise(66dbee39-6412-426f-b432-f8ddd74175a3)'
              Destination: 'AzureBlob'
              storage: '$(storageaccount)'
              ContainerName: '$web'
